language: rust
cache:
  - cargo
  - apt
dist: trusty
sudo: true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - libiberty-dev
    - g++
rust:
- stable
- beta
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - rust: stable
  - rust: beta
# before_script:
# - export PATH="$PATH:$HOME/.cargo/bin"
# - if [[ -z $(which rustfmt) ]] ; then cargo install rustfmt-nightly ; fi
script:
# - cargo fmt -- --write-mode=diff
- cargo build
- RUST_BACKTRACE=1 cargo test
after_success:
- scripts/coverage.sh
