language: rust
cache:
  - apt
dist: trusty
sudo: true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - libiberty-dev
    - g++
rust:
- stable
- beta
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - rust: stable
  - rust: beta
script: RUST_BACKTRACE=1 ./scripts/travis.sh
