[package]
name = "to-directory"
version = "0.1.0"
authors = ["Jason Campbell <jason@artifact.sh>"]
description = "EXPERIMENTAL - A CLI utility for bookmarking directories (with tab completion)."
homepage = "https://github.com/jxson/to-directory"
readme = "README.md"
keywords = [ "cd", "to" ]
license = "ISC"

[[bin]]
name = "to-directory"

# The library is only used for tests.
[lib]
name = "to"
path = "src/lib.rs"

[dependencies]
bincode = "0.8"
clap = "2.20.0"
error-chain = "0.11.0"
prettytable-rs = "^0.6"
serde = "1.0.10"
serde_derive = "1.0.10"
loggerv = "0.4.0"
log = "*"
time = "0.1.36"

[dev-dependencies]
assert_cli = "0.5.4"
tempdir = "0.3.5"
